export const eventList = [
  'onclick',
  // 'ondblclick',
  // 'onmousedown',
  // 'onmouseup',
  // 'onmouseover',
  // 'onmousemove',
  // 'onmouseout',
  // 'onmouseenter',
  // 'onmouseleave',
  // 'ontouchcancel',
  // 'ontouchend',
  // 'ontouchmove',
  // 'ontouchstart',
  // 'ondragstart',
  // 'ondrag',
  // 'ondragenter',
  // 'ondragleave',
  // 'ondragover',
  // 'ondrop',
  // 'ondragend',
  // 'onkeydown',
  // 'onkeypress',
  // 'onkeyup',
  // 'onabort',
  // 'onerror',
  // 'onresize',
  // 'onscroll',
  // 'onselect',
  // 'onchange',
  // 'onsubmit',
  // 'onreset',
  // 'onfocus',
  // 'onblur',
  // 'oninput',
  // 'onanimationend',
  // 'onanimationiteration',
  // 'onanimationstart',
  // 'oncontextmenu',
] as const

export type EventType = typeof eventList[number]
export const isEvent = (value: EventType) => eventList.includes(value)
